### ISSUE TITLE
GJ8

### ISSUE THREAD

**Issue by vick2075** [lorcan2440/Gauss-Jackson-Integrator#1]
Hi,

I'm having trouble with your first Python example:

Traceback (most recent call last):
  File "C:/Users/dell/Desktop/example2.py", line 19, in <module>
    t, xy, dxy, ddxy = gauss_jackson_8(ode_sys, (0, 60), np.array([1, 4]), np.array([2, -1]), 0.1)
  File "C:\Users/dell/Desktop\GJ8.py", line 155, in gauss_jackson_8
    s[4] = c1p
ValueError: could not broadcast input array from shape (2,) into shape (3,)

Can you please help me out?

Thanks
Vick

**Comment by lorcan2440** [comment]
Hi many thanks for letting me know, I've now fixed this. Please see the updated GJ8.py file and updated example code.

**Comment by vick2075** [comment]
Do you have a small n-body problem example?

**Comment by lorcan2440** [comment]
> Do you have a small n-body problem example?

Should be straightforward, I'll have a go at making one soon.

**Comment by vick2075** [comment]
I made one! It computed!
